# vim: set ft=yaml:
---
version: '2.3'

services:
  php53:
    extends:
      service: php53
      file: docker-compose-php-53.yml
  php54:
    extends:
      service: php54
      file: docker-compose-php-54.yml
  php55:
    extends:
      service: php55
      file: docker-compose-php-55.yml
  php56:
    extends:
      service: php56
      file: docker-compose-php-56.yml
  php70:
    extends:
      service: php70
      file: docker-compose-php-70.yml
  php71:
    extends:
      service: php71
      file: docker-compose-php-71.yml
  php72:
    extends:
      service: php72
      file: docker-compose-php-72.yml
  php73:
    extends:
      service: php73
      file: docker-compose-php-73.yml
  php74:
    extends:
      service: php74
      file: docker-compose-php-74.yml
  php80:
    extends:
      file: docker-compose-php-80.yml
      service: php80
  php81:
    extends:
      service: php81
      file: docker-compose-php-81.yml
  php82:
    extends:
      service: php82
      file: docker-compose-php-82.yml
  php:
    volumes:
      - ~/.config/composer:/home/devilbox/.composer:rw
      - ~/.gitconfig:/home/devilbox/.gitconfig:rw
      - ~/.ssh:/home/devilbox/.ssh:rw
  httpd:
    volumes:
      - ~/.config/composer:/home/devilbox/.composer:rw
      - ~/.gitconfig:/home/devilbox/.gitconfig:rw
      - ~/.ssh:/home/devilbox/.ssh:rw
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    networks:
      app_net:
        ipv4_address: 172.16.238.17
    volumes:
      - 'devilbox-minio:/data/minio'
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      retries: 3
      timeout: 5s
    # For ease of use always automatically start these:
    depends_on:
      - bind
      - php
      - httpd
  # -----------------------------------------------------------------------------------------------
  # Ngrok
  # -----------------------------------------------------------------------------------------------
  ngrok:
    image: devilbox/ngrok:0.3
    hostname: ngrok
    environment:
      - HTTP_TUNNELS=${NGROK_HTTP_TUNNELS:-httpd:httpd:80}
      - AUTHTOKEN=${NGROK_AUTHTOKEN:-}
      - REGION=${NGROK_REGION:-us}
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_NGROK:-4040}:4040"
    networks:
      app_net:
        ipv4_address: 172.16.238.202
    depends_on:
      - bind
      - php
      - httpd

volumes:
  # ------------------------------------------------------------
  # Misc
  # ------------------------------------------------------------
  devilbox-minio:
